/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package container;

import javax.swing.text.Document;
import templates.PlayerRace;
import util.Bundle;

/**
 *
 * @author Kendrick-Laptop
 */
public class BuilderRaceCard extends javax.swing.JPanel implements CardDataHolder{

    /**
     * Creates new form BuilderRaceCard
     */
    public BuilderRaceCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        combo_races = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_pane_flavor = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_race_deck_title.png"))); // NOI18N
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTextPane1.setEditable(false);
        jTextPane1.setText("There are many races in the realm of fantasy, each with advantageous features (both martial and magical). Try selecting a class with a race that have matching ability score requirements.");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(null);

        combo_races.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        combo_races.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_racesItemStateChanged(evt);
            }
        });
        jPanel3.add(combo_races);
        combo_races.setBounds(20, 40, 250, 20);

        txt_pane_flavor.setEditable(false);
        jScrollPane2.setViewportView(txt_pane_flavor);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(20, 72, 250, 380);

        jLabel2.setText("Select your Race here...");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 10, 250, 14);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_racesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_racesItemStateChanged
        BuilderFrame frame = BuilderFrame.getInstance();
        frame.updateValues();
    }//GEN-LAST:event_combo_racesItemStateChanged

    @Override
    public Document extractDocument(String key) {return null;}

    @Override
    public void putDocument(String key, String value) {}

    @Override
    public void getData(Bundle b) {
    }

    @Override
    public void update(Bundle b) {
    }

    public PlayerRace getSelectedRace() {
        return null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_races;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane txt_pane_flavor;
    // End of variables declaration//GEN-END:variables

    void storeInfo(Bundle character_info) {
    }
}
