/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package container;

import javax.swing.JButton;
import javax.swing.JPanel;
import util.Bundle;

/**
 *
 * @author Kendrick-Laptop
 */
public class BuilderFrame extends javax.swing.JFrame {
    
    private BuilderClassCard classCard;
    private BuilderRaceCard raceCard;
    private BuilderBackgroundCard backCard;
    private final BuilderDeck deck;
    public static final String CARD_CLASS = "Building Class";
    public static final String CARD_RACE =  "Building Race";
    public static final String CARD_BACKGROUND = "Building Background";
    
    private static class BuilderDeck extends Deck{

        private final JButton next;
        private final JButton previous;
        
        public BuilderDeck(JPanel holder, JButton next, JButton previous) {
            super(holder);
            previous.setEnabled(false);
            this.next = next;
            this.previous = previous;
        }

        @Override
        public void nextCard() {
            System.out.println(panels.size());
            if(!tail(current_item)){
                current_item++;
                previous.setEnabled(true);
                if(tail(current_item)){
                    next.setEnabled(false);
                }
            }
        }

        @Override
        public void previousCard() {
            if(!head(current_item)){
                current_item--;
                next.setEnabled(true);
                if(head(current_item)){
                    previous.setEnabled(false);
                }
            }
        }

        private boolean tail(int current_item) {
            return (panels.size()-1) == current_item;
        }
        
        private boolean head(int current_item){
            return (current_item == 0);
        }
        
       
        
    }

    public BuilderFrame(Bundle pullTemplates) {
        initComponents();
        classCard = new BuilderClassCard();
        raceCard = new BuilderRaceCard();
        backCard = new BuilderBackgroundCard();
        deck = new BuilderDeck(pan_deck, btn_next_card, btn_previous_card);
        deck.add(classCard, BuilderFrame.CARD_CLASS);
        deck.add(raceCard, BuilderFrame.CARD_RACE);
        deck.add(backCard, BuilderFrame.CARD_BACKGROUND);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_container = new javax.swing.JPanel();
        pan_deck_holder = new javax.swing.JPanel();
        pan_deck_controller = new javax.swing.JPanel();
        btn_next_card = new javax.swing.JButton();
        btn_previous_card = new javax.swing.JButton();
        pan_deck = new javax.swing.JPanel();
        panel_deck_stats = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pan_stats_offense = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        pan_stats_defense = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jProgressBar3 = new javax.swing.JProgressBar();
        jLabel10 = new javax.swing.JLabel();
        jProgressBar4 = new javax.swing.JProgressBar();
        jLabel11 = new javax.swing.JLabel();
        pan_stats_utility = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jProgressBar5 = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();
        jProgressBar6 = new javax.swing.JProgressBar();
        jLabel13 = new javax.swing.JLabel();
        pan_stats_ranged_melee = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jProgressBar7 = new javax.swing.JProgressBar();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jProgressBar8 = new javax.swing.JProgressBar();
        pan_stats_flavor_text = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Character Builder");

        pan_container.setBackground(new java.awt.Color(0, 51, 102));
        pan_container.setPreferredSize(new java.awt.Dimension(800, 600));
        pan_container.setLayout(new java.awt.BorderLayout());

        pan_deck_holder.setBackground(new java.awt.Color(0, 51, 102));
        pan_deck_holder.setPreferredSize(new java.awt.Dimension(300, 600));
        pan_deck_holder.setLayout(new java.awt.BorderLayout());

        pan_deck_controller.setBackground(new java.awt.Color(0, 51, 102));
        pan_deck_controller.setLayout(new java.awt.BorderLayout());

        btn_next_card.setBackground(new java.awt.Color(255, 255, 255));
        btn_next_card.setText("Next");
        btn_next_card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_next_cardActionPerformed(evt);
            }
        });
        pan_deck_controller.add(btn_next_card, java.awt.BorderLayout.LINE_END);

        btn_previous_card.setBackground(new java.awt.Color(255, 255, 255));
        btn_previous_card.setText("Previous");
        btn_previous_card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_previous_cardActionPerformed(evt);
            }
        });
        pan_deck_controller.add(btn_previous_card, java.awt.BorderLayout.LINE_START);

        pan_deck_holder.add(pan_deck_controller, java.awt.BorderLayout.PAGE_END);

        pan_deck.setBackground(new java.awt.Color(0, 51, 102));
        pan_deck.setLayout(new java.awt.CardLayout());
        pan_deck_holder.add(pan_deck, java.awt.BorderLayout.CENTER);

        pan_container.add(pan_deck_holder, java.awt.BorderLayout.LINE_START);

        panel_deck_stats.setBackground(new java.awt.Color(0, 25, 102));
        panel_deck_stats.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portrait_unknown.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        panel_deck_stats.add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Character Analyzer");
        jPanel2.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        pan_stats_offense.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Offense");
        pan_stats_offense.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(250, 103));
        jPanel4.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_magic.png"))); // NOI18N
        jLabel8.setText("Magic");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 10, 60, 30);

        jLabel9.setText("Martial");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 70, 50, 14);
        jPanel4.add(jProgressBar1);
        jProgressBar1.setBounds(80, 70, 146, 14);
        jPanel4.add(jProgressBar2);
        jProgressBar2.setBounds(80, 10, 146, 14);

        pan_stats_offense.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.add(pan_stats_offense);

        pan_stats_defense.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Defense");
        pan_stats_defense.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setPreferredSize(new java.awt.Dimension(250, 103));
        jPanel5.setLayout(null);
        jPanel5.add(jProgressBar3);
        jProgressBar3.setBounds(80, 10, 146, 14);

        jLabel10.setText("Magic");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(10, 10, 50, 14);
        jPanel5.add(jProgressBar4);
        jProgressBar4.setBounds(80, 70, 146, 14);

        jLabel11.setText("Martial");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(10, 70, 50, 14);

        pan_stats_defense.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel3.add(pan_stats_defense);

        pan_stats_utility.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Utility");
        pan_stats_utility.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setPreferredSize(new java.awt.Dimension(250, 103));
        jPanel6.setLayout(null);
        jPanel6.add(jProgressBar5);
        jProgressBar5.setBounds(80, 10, 146, 14);

        jLabel12.setText("Magic");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(10, 10, 50, 14);
        jPanel6.add(jProgressBar6);
        jProgressBar6.setBounds(80, 70, 146, 14);

        jLabel13.setText("Martial");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(10, 70, 50, 14);

        pan_stats_utility.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel3.add(pan_stats_utility);

        pan_stats_ranged_melee.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Playstyle");
        pan_stats_ranged_melee.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setPreferredSize(new java.awt.Dimension(250, 103));
        jPanel7.setLayout(null);
        jPanel7.add(jProgressBar7);
        jProgressBar7.setBounds(80, 10, 146, 14);

        jLabel14.setText("Ranged");
        jPanel7.add(jLabel14);
        jLabel14.setBounds(10, 10, 50, 14);

        jLabel15.setText("Melee");
        jPanel7.add(jLabel15);
        jLabel15.setBounds(10, 70, 50, 14);
        jPanel7.add(jProgressBar8);
        jProgressBar8.setBounds(80, 70, 146, 14);

        pan_stats_ranged_melee.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel3.add(pan_stats_ranged_melee);

        pan_stats_flavor_text.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Description");
        pan_stats_flavor_text.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jPanel8.setPreferredSize(new java.awt.Dimension(250, 103));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jTextPane1);

        jPanel8.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pan_stats_flavor_text.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel3.add(pan_stats_flavor_text);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        panel_deck_stats.add(jPanel2, java.awt.BorderLayout.CENTER);

        pan_container.add(panel_deck_stats, java.awt.BorderLayout.CENTER);

        getContentPane().add(pan_container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_previous_cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previous_cardActionPerformed
        deck.previousCard();
    }//GEN-LAST:event_btn_previous_cardActionPerformed

    private void btn_next_cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_next_cardActionPerformed
        deck.nextCard();
    }//GEN-LAST:event_btn_next_cardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_next_card;
    private javax.swing.JButton btn_previous_card;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    private javax.swing.JProgressBar jProgressBar7;
    private javax.swing.JProgressBar jProgressBar8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel pan_container;
    private javax.swing.JPanel pan_deck;
    private javax.swing.JPanel pan_deck_controller;
    private javax.swing.JPanel pan_deck_holder;
    private javax.swing.JPanel pan_stats_defense;
    private javax.swing.JPanel pan_stats_flavor_text;
    private javax.swing.JPanel pan_stats_offense;
    private javax.swing.JPanel pan_stats_ranged_melee;
    private javax.swing.JPanel pan_stats_utility;
    private javax.swing.JPanel panel_deck_stats;
    // End of variables declaration//GEN-END:variables
}
