package container;

import javax.swing.*;
import java.awt.*;

public class CharacterInfoPanel {
    public JPanel panel;
    private JTextField textField1;
    private JTextField textField2;
    private JTextField textField3;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        final JLabel label1 = new JLabel();
        label1.setText("Label");
        panel.add(label1);
        textField1 = new JTextField();
        textField1.setColumns(16);
        panel.add(textField1);
        final JLabel label2 = new JLabel();
        label2.setText("Label");
        panel.add(label2);
        textField2 = new JTextField();
        textField2.setColumns(12);
        panel.add(textField2);
        final JLabel label3 = new JLabel();
        label3.setText("Label");
        panel.add(label3);
        textField3 = new JTextField();
        textField3.setColumns(8);
        panel.add(textField3);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
