/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package container;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Kendrick
 */
public class CharacterFrame extends javax.swing.JFrame {

    /**
     * Creates new form CharacterFrame
     */
    public CharacterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        panForScrollPane = new javax.swing.JPanel();
        panCharInfo = new javax.swing.JPanel();
        lbl_charInfo = new javax.swing.JLabel();
        bdy_charInfo = new javax.swing.JPanel();
        pan_photo = new javax.swing.JPanel();
        lbl_characterImage = new javax.swing.JLabel();
        pan_info = new javax.swing.JPanel();
        lbl_charName = new javax.swing.JLabel();
        txt_charName = new javax.swing.JTextField();
        lbl_className = new javax.swing.JLabel();
        txt_className = new javax.swing.JTextField();
        lbl_raceName = new javax.swing.JLabel();
        txt_raceName = new javax.swing.JTextField();
        lbl_charSize = new javax.swing.JLabel();
        txt_sizeName = new javax.swing.JTextField();
        lbl_charWeight = new javax.swing.JLabel();
        txt_charWeight = new javax.swing.JTextField();
        lbl_charHeight = new javax.swing.JLabel();
        txt_charHeight = new javax.swing.JTextField();
        lbl_deity = new javax.swing.JLabel();
        txt_deity = new javax.swing.JTextField();
        lbl_alignment = new javax.swing.JLabel();
        txt_alignment = new javax.swing.JTextField();
        panAttributes = new javax.swing.JPanel();
        lbl_panAttributes = new javax.swing.JLabel();
        bdy_attributes = new javax.swing.JPanel();
        pan_strength = new javax.swing.JPanel();
        lbl_strengthTitle = new javax.swing.JLabel();
        pan_strBody = new javax.swing.JPanel();
        txt_strength = new javax.swing.JTextField();
        lbl_strengthModifierTitle = new javax.swing.JLabel();
        lbl_strengthModifier = new javax.swing.JLabel();
        pan_dexterity = new javax.swing.JPanel();
        lbl_dexterityTitle = new javax.swing.JLabel();
        pan_dexBody = new javax.swing.JPanel();
        txt_dexterity = new javax.swing.JTextField();
        lbl_dexterityModifierTitle = new javax.swing.JLabel();
        lbl_dexterityModifier = new javax.swing.JLabel();
        pan_constituion = new javax.swing.JPanel();
        lbl_constitutionTitle = new javax.swing.JLabel();
        pan_conBody = new javax.swing.JPanel();
        txt_constitution = new javax.swing.JTextField();
        lbl_constitutionModifierTitle = new javax.swing.JLabel();
        lbl_constitutionModifier = new javax.swing.JLabel();
        pan_intelligence = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pan_wisdom = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pan_charisma = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        panCombat = new javax.swing.JPanel();
        lbl_panCombat = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pan_offense = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pan_defense = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        pan_utility = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        panSkillsProfs = new javax.swing.JPanel();
        lbl_panSkillsProfs = new javax.swing.JLabel();
        bdy_skillsProfs = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jComboBox19 = new javax.swing.JComboBox<>();
        jTextField12 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jComboBox20 = new javax.swing.JComboBox<>();
        jTextField13 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jComboBox21 = new javax.swing.JComboBox<>();
        jTextField14 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jComboBox22 = new javax.swing.JComboBox<>();
        jTextField15 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jComboBox23 = new javax.swing.JComboBox<>();
        jTextField16 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jComboBox24 = new javax.swing.JComboBox<>();
        jTextField17 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jComboBox25 = new javax.swing.JComboBox<>();
        jTextField18 = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jComboBox26 = new javax.swing.JComboBox<>();
        jTextField19 = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jComboBox27 = new javax.swing.JComboBox<>();
        jTextField20 = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jComboBox28 = new javax.swing.JComboBox<>();
        jTextField21 = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jComboBox29 = new javax.swing.JComboBox<>();
        jTextField22 = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jComboBox30 = new javax.swing.JComboBox<>();
        jTextField23 = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jComboBox31 = new javax.swing.JComboBox<>();
        jTextField24 = new javax.swing.JTextField();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jComboBox32 = new javax.swing.JComboBox<>();
        jTextField25 = new javax.swing.JTextField();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jComboBox33 = new javax.swing.JComboBox<>();
        jTextField26 = new javax.swing.JTextField();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jComboBox34 = new javax.swing.JComboBox<>();
        jTextField27 = new javax.swing.JTextField();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jComboBox35 = new javax.swing.JComboBox<>();
        jTextField28 = new javax.swing.JTextField();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jComboBox36 = new javax.swing.JComboBox<>();
        jTextField29 = new javax.swing.JTextField();
        jLabel94 = new javax.swing.JLabel();
        panFeatures = new javax.swing.JPanel();
        lbl_panFeatures = new javax.swing.JLabel();
        bdy_features = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        panSpellsAndEquipment = new javax.swing.JPanel();
        lbl_panSpellsAndEquipment = new javax.swing.JLabel();
        bdy_spellsAndEquipment = new javax.swing.JPanel();
        panBackground = new javax.swing.JPanel();
        lbl_panBackground = new javax.swing.JLabel();
        bdy_background = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DND Character Sheet Editor");
        setPreferredSize(new java.awt.Dimension(820, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panForScrollPane.setBackground(new java.awt.Color(204, 204, 204));
        panForScrollPane.setMaximumSize(new java.awt.Dimension(800, 1200));
        panForScrollPane.setMinimumSize(new java.awt.Dimension(800, 1190));
        panForScrollPane.setPreferredSize(new java.awt.Dimension(800, 1200));
        panForScrollPane.setRequestFocusEnabled(false);
        panForScrollPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panCharInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panCharInfo.setMaximumSize(new java.awt.Dimension(200, 420));
        panCharInfo.setLayout(new java.awt.BorderLayout());

        lbl_charInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_charInfo.setText("Character Information");
        lbl_charInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl_charInfo.setPreferredSize(new java.awt.Dimension(120, 18));
        panCharInfo.add(lbl_charInfo, java.awt.BorderLayout.PAGE_START);

        bdy_charInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_photo.setLayout(new java.awt.BorderLayout());

        lbl_characterImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_characterImage.setText("Set Your Character Photo...");
        lbl_characterImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_characterImageMouseClicked(evt);
            }
        });
        pan_photo.add(lbl_characterImage, java.awt.BorderLayout.CENTER);

        bdy_charInfo.add(pan_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 150));

        pan_info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pan_info.setLayout(new java.awt.GridLayout(8, 2, -72, 0));

        lbl_charName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_charName.setText(" Name");
        lbl_charName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pan_info.add(lbl_charName);

        txt_charName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pan_info.add(txt_charName);

        lbl_className.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_className.setText(" Class");
        lbl_className.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pan_info.add(lbl_className);

        txt_className.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pan_info.add(txt_className);

        lbl_raceName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_raceName.setText(" Race");
        lbl_raceName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pan_info.add(lbl_raceName);

        txt_raceName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pan_info.add(txt_raceName);

        lbl_charSize.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_charSize.setText(" Size");
        lbl_charSize.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pan_info.add(lbl_charSize);

        txt_sizeName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pan_info.add(txt_sizeName);

        lbl_charWeight.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_charWeight.setText(" Weight");
        lbl_charWeight.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pan_info.add(lbl_charWeight);

        txt_charWeight.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pan_info.add(txt_charWeight);

        lbl_charHeight.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_charHeight.setText(" Height");
        lbl_charHeight.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pan_info.add(lbl_charHeight);

        txt_charHeight.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pan_info.add(txt_charHeight);

        lbl_deity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_deity.setText(" Deity");
        lbl_deity.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pan_info.add(lbl_deity);

        txt_deity.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pan_info.add(txt_deity);

        lbl_alignment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_alignment.setText(" Alignment");
        lbl_alignment.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pan_info.add(lbl_alignment);

        txt_alignment.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pan_info.add(txt_alignment);

        bdy_charInfo.add(pan_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 198, 250));

        panCharInfo.add(bdy_charInfo, java.awt.BorderLayout.CENTER);

        panForScrollPane.add(panCharInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 420));

        panAttributes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panAttributes.setMaximumSize(new java.awt.Dimension(550, 150));
        panAttributes.setLayout(new java.awt.BorderLayout());

        lbl_panAttributes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_panAttributes.setText("Attributes");
        lbl_panAttributes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panAttributes.add(lbl_panAttributes, java.awt.BorderLayout.PAGE_START);

        bdy_attributes.setLayout(new java.awt.GridLayout(1, 6));

        pan_strength.setLayout(new java.awt.GridLayout(4, 3));

        lbl_strengthTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_strengthTitle.setText("Strength");
        pan_strength.add(lbl_strengthTitle);

        pan_strBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_strength.setColumns(4);
        txt_strength.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_strength.setText("10");
        pan_strBody.add(txt_strength, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 30));

        pan_strength.add(pan_strBody);

        lbl_strengthModifierTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_strengthModifierTitle.setText("Modifier");
        pan_strength.add(lbl_strengthModifierTitle);

        lbl_strengthModifier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_strengthModifier.setText("0");
        pan_strength.add(lbl_strengthModifier);

        bdy_attributes.add(pan_strength);

        pan_dexterity.setLayout(new java.awt.GridLayout(4, 3));

        lbl_dexterityTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dexterityTitle.setText("Dexterity");
        pan_dexterity.add(lbl_dexterityTitle);

        pan_dexBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_dexterity.setColumns(4);
        txt_dexterity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_dexterity.setText("10");
        pan_dexBody.add(txt_dexterity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 30));

        pan_dexterity.add(pan_dexBody);

        lbl_dexterityModifierTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dexterityModifierTitle.setText("Modifier");
        pan_dexterity.add(lbl_dexterityModifierTitle);

        lbl_dexterityModifier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dexterityModifier.setText("0");
        pan_dexterity.add(lbl_dexterityModifier);

        bdy_attributes.add(pan_dexterity);

        pan_constituion.setLayout(new java.awt.GridLayout(4, 3));

        lbl_constitutionTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_constitutionTitle.setText("Constituion");
        pan_constituion.add(lbl_constitutionTitle);

        pan_conBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_constitution.setColumns(4);
        txt_constitution.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_constitution.setText("10");
        pan_conBody.add(txt_constitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 30));

        pan_constituion.add(pan_conBody);

        lbl_constitutionModifierTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_constitutionModifierTitle.setText("Modifier");
        pan_constituion.add(lbl_constitutionModifierTitle);

        lbl_constitutionModifier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_constitutionModifier.setText("0");
        pan_constituion.add(lbl_constitutionModifier);

        bdy_attributes.add(pan_constituion);

        pan_intelligence.setLayout(new java.awt.GridLayout(4, 3));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Intelligence");
        pan_intelligence.add(jLabel13);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField5.setColumns(4);
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("10");
        jPanel13.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 30));

        pan_intelligence.add(jPanel13);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Modifier");
        pan_intelligence.add(jLabel14);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("0");
        pan_intelligence.add(jLabel15);

        bdy_attributes.add(pan_intelligence);

        pan_wisdom.setLayout(new java.awt.GridLayout(4, 3));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Wisdom");
        pan_wisdom.add(jLabel16);

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField6.setColumns(4);
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("10");
        jPanel15.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 30));

        pan_wisdom.add(jPanel15);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Modifier");
        pan_wisdom.add(jLabel17);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("0");
        pan_wisdom.add(jLabel18);

        bdy_attributes.add(pan_wisdom);

        pan_charisma.setLayout(new java.awt.GridLayout(4, 3));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Charisma");
        pan_charisma.add(jLabel19);

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField7.setColumns(4);
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("10");
        jPanel17.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 30));

        pan_charisma.add(jPanel17);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Modifier");
        pan_charisma.add(jLabel20);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("0");
        pan_charisma.add(jLabel21);

        bdy_attributes.add(pan_charisma);

        panAttributes.add(bdy_attributes, java.awt.BorderLayout.CENTER);

        panForScrollPane.add(panAttributes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 550, 150));

        panCombat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panCombat.setMaximumSize(new java.awt.Dimension(550, 260));
        panCombat.setLayout(new java.awt.BorderLayout());

        lbl_panCombat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_panCombat.setText("Combat & Utility");
        lbl_panCombat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panCombat.add(lbl_panCombat, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        pan_offense.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Offensive");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pan_offense.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Weapon Name");

        jTextField2.setColumns(6);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Attack Bonus");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Attack Type");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pan_offense.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(pan_offense);

        pan_defense.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Defensive");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pan_defense.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridLayout(2, 5));

        jLabel11.setText("AC");
        jPanel5.add(jLabel11);

        jLabel25.setText("=");
        jPanel5.add(jLabel25);

        jLabel26.setText("Armor");
        jPanel5.add(jLabel26);

        jLabel27.setText("Dex");
        jPanel5.add(jLabel27);

        jLabel34.setText("Bonus");
        jPanel5.add(jLabel34);

        jLabel35.setText("0");
        jPanel5.add(jLabel35);

        jLabel36.setText("=");
        jPanel5.add(jLabel36);

        jLabel37.setText("0");
        jPanel5.add(jLabel37);

        jLabel38.setText("0");
        jPanel5.add(jLabel38);
        jPanel5.add(jTextField10);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Common Saves");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jPanel9.setLayout(new java.awt.GridLayout(4, 4));

        jLabel8.setText("Type");
        jPanel9.add(jLabel8);

        jLabel9.setText("Total");
        jPanel9.add(jLabel9);

        jLabel10.setText("Modifier");
        jPanel9.add(jLabel10);

        jLabel12.setText("Bonus");
        jPanel9.add(jLabel12);

        jLabel23.setText("DEX");
        jPanel9.add(jLabel23);

        jLabel24.setText("0");
        jPanel9.add(jLabel24);

        jLabel28.setText("0");
        jPanel9.add(jLabel28);
        jPanel9.add(jTextField4);

        jLabel29.setText("WIS");
        jPanel9.add(jLabel29);

        jLabel30.setText("0");
        jPanel9.add(jLabel30);

        jLabel31.setText("0");
        jPanel9.add(jLabel31);
        jPanel9.add(jTextField8);

        jLabel32.setText("CHA");
        jPanel9.add(jLabel32);

        jLabel33.setText("0");
        jPanel9.add(jLabel33);

        jLabel22.setText("0");
        jPanel9.add(jLabel22);
        jPanel9.add(jTextField9);

        jPanel8.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel8, java.awt.BorderLayout.CENTER);

        pan_defense.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(pan_defense);

        pan_utility.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Utility and Survival");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pan_utility.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setLayout(new java.awt.GridLayout(2, 4));

        jLabel44.setText("Speed ");
        jPanel6.add(jLabel44);

        jLabel45.setText("= Base");
        jPanel6.add(jLabel45);

        jLabel46.setText("+");
        jPanel6.add(jLabel46);

        jLabel47.setText("Bonus");
        jPanel6.add(jLabel47);

        jLabel48.setText("30");
        jPanel6.add(jLabel48);

        jLabel49.setText("30");
        jPanel6.add(jLabel49);

        jLabel50.setText("+");
        jPanel6.add(jLabel50);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField3);

        jPanel4.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(2, 4));

        jLabel39.setText("Initiative");
        jPanel7.add(jLabel39);

        jLabel40.setText("= Dex");
        jPanel7.add(jLabel40);

        jLabel41.setText("+");
        jPanel7.add(jLabel41);

        jLabel42.setText("Bonus");
        jPanel7.add(jLabel42);

        jLabel43.setText("0");
        jPanel7.add(jLabel43);

        jLabel51.setText("0");
        jPanel7.add(jLabel51);

        jLabel52.setText("+");
        jPanel7.add(jLabel52);

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField11);

        jPanel4.add(jPanel7);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel53.setText("Damage Resistances");
        jPanel11.add(jLabel53, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel11.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel11);

        pan_utility.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(pan_utility);

        panCombat.add(jPanel1, java.awt.BorderLayout.CENTER);

        panForScrollPane.add(panCombat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 550, 260));

        panSkillsProfs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panSkillsProfs.setMaximumSize(new java.awt.Dimension(200, 420));
        panSkillsProfs.setLayout(new java.awt.BorderLayout());

        lbl_panSkillsProfs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_panSkillsProfs.setText("Skills and Proficiencies ");
        lbl_panSkillsProfs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panSkillsProfs.add(lbl_panSkillsProfs, java.awt.BorderLayout.PAGE_START);

        bdy_skillsProfs.setLayout(new java.awt.GridLayout(19, 4));

        jLabel54.setText("Name");
        jLabel54.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bdy_skillsProfs.add(jLabel54);

        jLabel55.setText("Proficient");
        jLabel55.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bdy_skillsProfs.add(jLabel55);

        jLabel56.setText("Bonus");
        jLabel56.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bdy_skillsProfs.add(jLabel56);

        jLabel57.setText("Total");
        jLabel57.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bdy_skillsProfs.add(jLabel57);

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel59.setText("Athletics (STR)");
        bdy_skillsProfs.add(jLabel59);

        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox19);

        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("0");
        bdy_skillsProfs.add(jTextField12);

        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("0");
        bdy_skillsProfs.add(jLabel63);

        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel64.setText("Acrobatics (DEX)");
        bdy_skillsProfs.add(jLabel64);

        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox20);

        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("0");
        bdy_skillsProfs.add(jTextField13);

        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("0");
        bdy_skillsProfs.add(jLabel60);

        jLabel65.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel65.setText("Sleight of Hand (DEX)");
        bdy_skillsProfs.add(jLabel65);

        jComboBox21.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox21);

        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("0");
        bdy_skillsProfs.add(jTextField14);

        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("0");
        bdy_skillsProfs.add(jLabel61);

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel66.setText("Stealth (DEX)");
        bdy_skillsProfs.add(jLabel66);

        jComboBox22.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox22);

        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setText("0");
        bdy_skillsProfs.add(jTextField15);

        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("0");
        bdy_skillsProfs.add(jLabel62);

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel67.setText("Arcana (INT)");
        bdy_skillsProfs.add(jLabel67);

        jComboBox23.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox23);

        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText("0");
        bdy_skillsProfs.add(jTextField16);

        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("0");
        bdy_skillsProfs.add(jLabel68);

        jLabel69.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel69.setText("History (INT)");
        bdy_skillsProfs.add(jLabel69);

        jComboBox24.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox24);

        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setText("0");
        bdy_skillsProfs.add(jTextField17);

        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("0");
        bdy_skillsProfs.add(jLabel70);

        jLabel71.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel71.setText("Investigation (INT)");
        bdy_skillsProfs.add(jLabel71);

        jComboBox25.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox25);

        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText("0");
        bdy_skillsProfs.add(jTextField18);

        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("0");
        bdy_skillsProfs.add(jLabel72);

        jLabel73.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel73.setText("Nature (INT)");
        bdy_skillsProfs.add(jLabel73);

        jComboBox26.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox26);

        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setText("0");
        bdy_skillsProfs.add(jTextField19);

        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel74.setText("0");
        bdy_skillsProfs.add(jLabel74);

        jLabel75.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel75.setText("Religion (INT)");
        bdy_skillsProfs.add(jLabel75);

        jComboBox27.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox27);

        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setText("0");
        bdy_skillsProfs.add(jTextField20);

        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel76.setText("0");
        bdy_skillsProfs.add(jLabel76);

        jLabel77.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel77.setText("Animal Handling (WIS)");
        bdy_skillsProfs.add(jLabel77);

        jComboBox28.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox28);

        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setText("0");
        bdy_skillsProfs.add(jTextField21);

        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel78.setText("0");
        bdy_skillsProfs.add(jLabel78);

        jLabel79.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel79.setText("Insight (WIS)");
        bdy_skillsProfs.add(jLabel79);

        jComboBox29.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox29);

        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setText("0");
        bdy_skillsProfs.add(jTextField22);

        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel80.setText("0");
        bdy_skillsProfs.add(jLabel80);

        jLabel81.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel81.setText("Medicine (WIS)");
        bdy_skillsProfs.add(jLabel81);

        jComboBox30.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox30);

        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField23.setText("0");
        bdy_skillsProfs.add(jTextField23);

        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel82.setText("0");
        bdy_skillsProfs.add(jLabel82);

        jLabel83.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel83.setText("Perception (WIS)");
        bdy_skillsProfs.add(jLabel83);

        jComboBox31.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox31);

        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.setText("0");
        bdy_skillsProfs.add(jTextField24);

        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel84.setText("0");
        bdy_skillsProfs.add(jLabel84);

        jLabel85.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel85.setText("Survival (WIS)");
        bdy_skillsProfs.add(jLabel85);

        jComboBox32.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox32);

        jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField25.setText("0");
        bdy_skillsProfs.add(jTextField25);

        jLabel86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel86.setText("0");
        bdy_skillsProfs.add(jLabel86);

        jLabel87.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel87.setText("Deception (CHA)");
        bdy_skillsProfs.add(jLabel87);

        jComboBox33.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox33);

        jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField26.setText("0");
        bdy_skillsProfs.add(jTextField26);

        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel88.setText("0");
        bdy_skillsProfs.add(jLabel88);

        jLabel89.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel89.setText("Intimidation (CHA)");
        bdy_skillsProfs.add(jLabel89);

        jComboBox34.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox34);

        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField27.setText("0");
        bdy_skillsProfs.add(jTextField27);

        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel90.setText("0");
        bdy_skillsProfs.add(jLabel90);

        jLabel91.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel91.setText("Performance (CHA)");
        bdy_skillsProfs.add(jLabel91);

        jComboBox35.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox35);

        jTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField28.setText("0");
        bdy_skillsProfs.add(jTextField28);

        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel92.setText("0");
        bdy_skillsProfs.add(jLabel92);

        jLabel93.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel93.setText("Persuasion (CHA)");
        bdy_skillsProfs.add(jLabel93);

        jComboBox36.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        bdy_skillsProfs.add(jComboBox36);

        jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField29.setText("0");
        bdy_skillsProfs.add(jTextField29);

        jLabel94.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel94.setText("0");
        bdy_skillsProfs.add(jLabel94);

        panSkillsProfs.add(bdy_skillsProfs, java.awt.BorderLayout.CENTER);

        panForScrollPane.add(panSkillsProfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 440, 420));

        panFeatures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panFeatures.setMaximumSize(new java.awt.Dimension(550, 420));
        panFeatures.setLayout(new java.awt.BorderLayout());

        lbl_panFeatures.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_panFeatures.setText("Feats, Class Features, and Racial Features");
        lbl_panFeatures.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panFeatures.add(lbl_panFeatures, java.awt.BorderLayout.PAGE_START);

        bdy_features.setLayout(new java.awt.BorderLayout());

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        bdy_features.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        panFeatures.add(bdy_features, java.awt.BorderLayout.CENTER);

        panForScrollPane.add(panFeatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 310, 420));

        panSpellsAndEquipment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panSpellsAndEquipment.setMaximumSize(new java.awt.Dimension(540, 320));
        panSpellsAndEquipment.setLayout(new java.awt.BorderLayout());

        lbl_panSpellsAndEquipment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_panSpellsAndEquipment.setText("Spellbook and Inventory");
        lbl_panSpellsAndEquipment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panSpellsAndEquipment.add(lbl_panSpellsAndEquipment, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout bdy_spellsAndEquipmentLayout = new javax.swing.GroupLayout(bdy_spellsAndEquipment);
        bdy_spellsAndEquipment.setLayout(bdy_spellsAndEquipmentLayout);
        bdy_spellsAndEquipmentLayout.setHorizontalGroup(
            bdy_spellsAndEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        bdy_spellsAndEquipmentLayout.setVerticalGroup(
            bdy_spellsAndEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        panSpellsAndEquipment.add(bdy_spellsAndEquipment, java.awt.BorderLayout.CENTER);

        panForScrollPane.add(panSpellsAndEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 870, 540, 320));

        panBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panBackground.setLayout(new java.awt.BorderLayout());

        lbl_panBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_panBackground.setText("Background");
        lbl_panBackground.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panBackground.add(lbl_panBackground, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout bdy_backgroundLayout = new javax.swing.GroupLayout(bdy_background);
        bdy_background.setLayout(bdy_backgroundLayout);
        bdy_backgroundLayout.setHorizontalGroup(
            bdy_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        bdy_backgroundLayout.setVerticalGroup(
            bdy_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        panBackground.add(bdy_background, java.awt.BorderLayout.CENTER);

        panForScrollPane.add(panBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 870, 210, 320));

        scrollPane.setViewportView(panForScrollPane);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem1.setText("New...");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Open...");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Save...");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tools");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_characterImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_characterImageMouseClicked
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG Images", "jpg");
        chooser.setFileFilter(filter);
        int condition = chooser.showOpenDialog(null);
        if(condition == JFileChooser.APPROVE_OPTION){
            setLblImageToFile(chooser.getSelectedFile());
        }
    }//GEN-LAST:event_lbl_characterImageMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bdy_attributes;
    private javax.swing.JPanel bdy_background;
    private javax.swing.JPanel bdy_charInfo;
    private javax.swing.JPanel bdy_features;
    private javax.swing.JPanel bdy_skillsProfs;
    private javax.swing.JPanel bdy_spellsAndEquipment;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JComboBox<String> jComboBox20;
    private javax.swing.JComboBox<String> jComboBox21;
    private javax.swing.JComboBox<String> jComboBox22;
    private javax.swing.JComboBox<String> jComboBox23;
    private javax.swing.JComboBox<String> jComboBox24;
    private javax.swing.JComboBox<String> jComboBox25;
    private javax.swing.JComboBox<String> jComboBox26;
    private javax.swing.JComboBox<String> jComboBox27;
    private javax.swing.JComboBox<String> jComboBox28;
    private javax.swing.JComboBox<String> jComboBox29;
    private javax.swing.JComboBox<String> jComboBox30;
    private javax.swing.JComboBox<String> jComboBox31;
    private javax.swing.JComboBox<String> jComboBox32;
    private javax.swing.JComboBox<String> jComboBox33;
    private javax.swing.JComboBox<String> jComboBox34;
    private javax.swing.JComboBox<String> jComboBox35;
    private javax.swing.JComboBox<String> jComboBox36;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lbl_alignment;
    private javax.swing.JLabel lbl_charHeight;
    private javax.swing.JLabel lbl_charInfo;
    private javax.swing.JLabel lbl_charName;
    private javax.swing.JLabel lbl_charSize;
    private javax.swing.JLabel lbl_charWeight;
    private javax.swing.JLabel lbl_characterImage;
    private javax.swing.JLabel lbl_className;
    private javax.swing.JLabel lbl_constitutionModifier;
    private javax.swing.JLabel lbl_constitutionModifierTitle;
    private javax.swing.JLabel lbl_constitutionTitle;
    private javax.swing.JLabel lbl_deity;
    private javax.swing.JLabel lbl_dexterityModifier;
    private javax.swing.JLabel lbl_dexterityModifierTitle;
    private javax.swing.JLabel lbl_dexterityTitle;
    private javax.swing.JLabel lbl_panAttributes;
    private javax.swing.JLabel lbl_panBackground;
    private javax.swing.JLabel lbl_panCombat;
    private javax.swing.JLabel lbl_panFeatures;
    private javax.swing.JLabel lbl_panSkillsProfs;
    private javax.swing.JLabel lbl_panSpellsAndEquipment;
    private javax.swing.JLabel lbl_raceName;
    private javax.swing.JLabel lbl_strengthModifier;
    private javax.swing.JLabel lbl_strengthModifierTitle;
    private javax.swing.JLabel lbl_strengthTitle;
    private javax.swing.JPanel panAttributes;
    private javax.swing.JPanel panBackground;
    private javax.swing.JPanel panCharInfo;
    private javax.swing.JPanel panCombat;
    private javax.swing.JPanel panFeatures;
    private javax.swing.JPanel panForScrollPane;
    private javax.swing.JPanel panSkillsProfs;
    private javax.swing.JPanel panSpellsAndEquipment;
    private javax.swing.JPanel pan_charisma;
    private javax.swing.JPanel pan_conBody;
    private javax.swing.JPanel pan_constituion;
    private javax.swing.JPanel pan_defense;
    private javax.swing.JPanel pan_dexBody;
    private javax.swing.JPanel pan_dexterity;
    private javax.swing.JPanel pan_info;
    private javax.swing.JPanel pan_intelligence;
    private javax.swing.JPanel pan_offense;
    private javax.swing.JPanel pan_photo;
    private javax.swing.JPanel pan_strBody;
    private javax.swing.JPanel pan_strength;
    private javax.swing.JPanel pan_utility;
    private javax.swing.JPanel pan_wisdom;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField txt_alignment;
    private javax.swing.JTextField txt_charHeight;
    private javax.swing.JTextField txt_charName;
    private javax.swing.JTextField txt_charWeight;
    private javax.swing.JTextField txt_className;
    private javax.swing.JTextField txt_constitution;
    private javax.swing.JTextField txt_deity;
    private javax.swing.JTextField txt_dexterity;
    private javax.swing.JTextField txt_raceName;
    private javax.swing.JTextField txt_sizeName;
    private javax.swing.JTextField txt_strength;
    // End of variables declaration//GEN-END:variables

    private void setLblImageToFile(File selectedFile) {
        ImageIcon photo = new ImageIcon(selectedFile.getAbsolutePath());
        //https://stackoverflow.com/questions/6714045/how-to-resize-jlabel-imageicon for resizing
        Image image = photo.getImage(); // transform it 
        Image newimg = image.getScaledInstance(190, 140,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        photo = new ImageIcon(newimg);  // transform it back
        lbl_characterImage.setText("");
        lbl_characterImage.setIcon(photo);

    }
}
