/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package container;

import constants.KEY;
import javax.swing.text.Document;
import util.Bundle;
import util.DataIntegrity;

/**
 *
 * @author Kendrick
 */
public class DefensePanel extends javax.swing.JPanel implements CardDataHolder{

    /**
     * Creates new form DefensePanel
     */
    public DefensePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        lbl_ac_title = new javax.swing.JLabel();
        lbl_equal_sign = new javax.swing.JLabel();
        lbl_armor_title = new javax.swing.JLabel();
        lbl_dex_bonus_title = new javax.swing.JLabel();
        lbl_bonus_ac_title = new javax.swing.JLabel();
        lbl_ac_total = new javax.swing.JLabel();
        lbl_equal_sign2 = new javax.swing.JLabel();
        lbl_ac = new javax.swing.JLabel();
        lbl_ac_dex = new javax.swing.JLabel();
        txt_extra_ac_bonus = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_defense_bonuses = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_damage_resist = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridLayout(2, 5));

        lbl_ac_title.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_ac_title.setText("AC");
        jPanel5.add(lbl_ac_title);

        lbl_equal_sign.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_equal_sign.setText("= ");
        jPanel5.add(lbl_equal_sign);

        lbl_armor_title.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_armor_title.setText("ARM");
        jPanel5.add(lbl_armor_title);

        lbl_dex_bonus_title.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_dex_bonus_title.setText("DEX");
        jPanel5.add(lbl_dex_bonus_title);

        lbl_bonus_ac_title.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_bonus_ac_title.setText("EXTRA");
        jPanel5.add(lbl_bonus_ac_title);

        lbl_ac_total.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_ac_total.setText("0");
        jPanel5.add(lbl_ac_total);

        lbl_equal_sign2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_equal_sign2.setText("=");
        jPanel5.add(lbl_equal_sign2);

        lbl_ac.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_ac.setText("0");
        jPanel5.add(lbl_ac);

        lbl_ac_dex.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_ac_dex.setText("0");
        jPanel5.add(lbl_ac_dex);

        txt_extra_ac_bonus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txt_extra_ac_bonus.setText("0");
        jPanel5.add(txt_extra_ac_bonus);

        add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Defense Bonuses");
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txt_defense_bonuses.setColumns(20);
        txt_defense_bonuses.setLineWrap(true);
        txt_defense_bonuses.setRows(5);
        jScrollPane2.setViewportView(txt_defense_bonuses);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.PAGE_END);

        jPanel8.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Damage Resistances");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txt_damage_resist.setColumns(20);
        txt_damage_resist.setLineWrap(true);
        txt_damage_resist.setRows(5);
        jScrollPane1.setViewportView(txt_damage_resist);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel8, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_ac;
    private javax.swing.JLabel lbl_ac_dex;
    private javax.swing.JLabel lbl_ac_title;
    private javax.swing.JLabel lbl_ac_total;
    private javax.swing.JLabel lbl_armor_title;
    private javax.swing.JLabel lbl_bonus_ac_title;
    private javax.swing.JLabel lbl_dex_bonus_title;
    private javax.swing.JLabel lbl_equal_sign;
    private javax.swing.JLabel lbl_equal_sign2;
    private javax.swing.JTextArea txt_damage_resist;
    private javax.swing.JTextArea txt_defense_bonuses;
    public javax.swing.JTextField txt_extra_ac_bonus;
    // End of variables declaration//GEN-END:variables


    void setArmorValues(int dex_mod, int dex_cap, int ac) {
        int armor_dex = 0;
        if(dex_cap == 0 || dex_mod < dex_cap){
            armor_dex = dex_mod;
        }
        else{
            armor_dex = dex_cap;
        }
        int extraAC = Integer.parseInt(txt_extra_ac_bonus.getText());
        int totalAC = extraAC + armor_dex + ac;
        lbl_ac_dex.setText(Integer.toString(armor_dex));
        lbl_ac.setText(Integer.toString(ac));
        lbl_ac_total.setText(Integer.toString(totalAC));
    }

    @Override
    public Document extractDocument(String key) {
        switch(key){
            case KEY.K_DEFENSE_AC_EXTRA:return txt_extra_ac_bonus.getDocument();
            case KEY.K_DEFENSE_DR:return txt_damage_resist.getDocument();
            case KEY.K_DEFENSE_BONUSES:return txt_defense_bonuses.getDocument();
        }
        return null;
    }

    @Override
    public void putDocument(String key, String value) {
    }

    @Override
    public void getData(Bundle b) {
        b.putString(KEY.K_DEFENSE_AC_EXTRA, txt_extra_ac_bonus.getText());
        b.putString(KEY.K_DEFENSE_DR, txt_damage_resist.getText());
        b.putString(KEY.K_DEFENSE_BONUSES, txt_defense_bonuses.getText());
    }

    @Override
    public void update(Bundle b) {
        String acExtra = b.getString(KEY.K_DEFENSE_AC_EXTRA);
        String dr = b.getString(KEY.K_DEFENSE_DR);
        String dfB = b.getString(KEY.K_DEFENSE_BONUSES);
        
        if(DataIntegrity.isNumeric(acExtra)){
            txt_extra_ac_bonus.setText(acExtra);
        }
        else{
            txt_extra_ac_bonus.setText(DataIntegrity.DEFAULT_ZERO_STR);
        }
        
        txt_damage_resist.setText(dr);
        txt_defense_bonuses.setText(dfB);
        
    }
}
