/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package container;

import app.AppManager;
import constants.KEY;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;
import util.Bundle;

/**
 *
 * @author Kendrick
 */
public class SkillsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SkillsPanel
     */
    public SkillsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_skillsColName = new javax.swing.JLabel();
        lbl_skillsColProf = new javax.swing.JLabel();
        lbl_skillsColBonus = new javax.swing.JLabel();
        lbl_skillsColTotal = new javax.swing.JLabel();
        lbl_athleticsName = new javax.swing.JLabel();
        prof_athletics = new javax.swing.JComboBox<>();
        bonus_athletics = new javax.swing.JTextField();
        total_athletics = new javax.swing.JLabel();
        lbl_acrobaticsName = new javax.swing.JLabel();
        prof_acrobatics = new javax.swing.JComboBox<>();
        bonus_acrobatics = new javax.swing.JTextField();
        total_acrobatics = new javax.swing.JLabel();
        lbl_sleightName = new javax.swing.JLabel();
        prof_sleight = new javax.swing.JComboBox<>();
        bonus_sleight = new javax.swing.JTextField();
        total_sleight = new javax.swing.JLabel();
        lbl_stealthName = new javax.swing.JLabel();
        prof_stealth = new javax.swing.JComboBox<>();
        bonus_stealth = new javax.swing.JTextField();
        total_stealth = new javax.swing.JLabel();
        lbl_arcanaName = new javax.swing.JLabel();
        prof_arcana = new javax.swing.JComboBox<>();
        bonus_arcana = new javax.swing.JTextField();
        total_arcana = new javax.swing.JLabel();
        lbl_historyName = new javax.swing.JLabel();
        prof_history = new javax.swing.JComboBox<>();
        bonus_history = new javax.swing.JTextField();
        total_history = new javax.swing.JLabel();
        lbl_investigationName = new javax.swing.JLabel();
        prof_investigation = new javax.swing.JComboBox<>();
        bonus_investigation = new javax.swing.JTextField();
        total_investigation = new javax.swing.JLabel();
        lbl_natureName = new javax.swing.JLabel();
        prof_nature = new javax.swing.JComboBox<>();
        bonus_nature = new javax.swing.JTextField();
        total_nature = new javax.swing.JLabel();
        lbl_religionName = new javax.swing.JLabel();
        prof_religion = new javax.swing.JComboBox<>();
        bonus_religion = new javax.swing.JTextField();
        total_religion = new javax.swing.JLabel();
        lbl_animalHandlingName = new javax.swing.JLabel();
        prof_animalHandling = new javax.swing.JComboBox<>();
        bonus_animalHandling = new javax.swing.JTextField();
        total_animalHandling = new javax.swing.JLabel();
        lbl_insightName = new javax.swing.JLabel();
        prof_insight = new javax.swing.JComboBox<>();
        bonus_insight = new javax.swing.JTextField();
        total_insight = new javax.swing.JLabel();
        lbl_medicineName = new javax.swing.JLabel();
        prof_medicine = new javax.swing.JComboBox<>();
        bonus_medicine = new javax.swing.JTextField();
        total_medicine = new javax.swing.JLabel();
        lbl_perceptionName = new javax.swing.JLabel();
        prof_perception = new javax.swing.JComboBox<>();
        bonus_perception = new javax.swing.JTextField();
        total_perception = new javax.swing.JLabel();
        lbl_survivalName = new javax.swing.JLabel();
        prof_survival = new javax.swing.JComboBox<>();
        bonus_survival = new javax.swing.JTextField();
        total_survival = new javax.swing.JLabel();
        lbl_deceptionName = new javax.swing.JLabel();
        prof_deception = new javax.swing.JComboBox<>();
        bonus_deception = new javax.swing.JTextField();
        total_deception = new javax.swing.JLabel();
        lbl_intimidationName = new javax.swing.JLabel();
        prof_intimidation = new javax.swing.JComboBox<>();
        bonus_intimidation = new javax.swing.JTextField();
        total_intimidation = new javax.swing.JLabel();
        lbl_performanceName = new javax.swing.JLabel();
        prof_performance = new javax.swing.JComboBox<>();
        bonus_performance = new javax.swing.JTextField();
        total_performance = new javax.swing.JLabel();
        lbl_persuasionName = new javax.swing.JLabel();
        prof_persuasion = new javax.swing.JComboBox<>();
        bonus_persuasion = new javax.swing.JTextField();
        total_persuasion = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(19, 4));

        lbl_skillsColName.setText("Name");
        lbl_skillsColName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(lbl_skillsColName);

        lbl_skillsColProf.setText("Proficient");
        lbl_skillsColProf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(lbl_skillsColProf);

        lbl_skillsColBonus.setText("Bonus");
        lbl_skillsColBonus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(lbl_skillsColBonus);

        lbl_skillsColTotal.setText("Total");
        lbl_skillsColTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(lbl_skillsColTotal);

        lbl_athleticsName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_athleticsName.setText("Athletics (STR)");
        lbl_athleticsName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_athleticsName);

        prof_athletics.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_athletics);

        bonus_athletics.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_athletics.setText("0");
        add(bonus_athletics);

        total_athletics.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_athletics.setText("0");
        add(total_athletics);

        lbl_acrobaticsName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_acrobaticsName.setText("Acrobatics (DEX)");
        lbl_acrobaticsName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_acrobaticsName);

        prof_acrobatics.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_acrobatics);

        bonus_acrobatics.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_acrobatics.setText("0");
        add(bonus_acrobatics);

        total_acrobatics.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_acrobatics.setText("0");
        add(total_acrobatics);

        lbl_sleightName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_sleightName.setText("Sleight of Hand (DEX)");
        lbl_sleightName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_sleightName);

        prof_sleight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_sleight);

        bonus_sleight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_sleight.setText("0");
        add(bonus_sleight);

        total_sleight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_sleight.setText("0");
        add(total_sleight);

        lbl_stealthName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_stealthName.setText("Stealth (DEX)");
        lbl_stealthName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_stealthName);

        prof_stealth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_stealth);

        bonus_stealth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_stealth.setText("0");
        add(bonus_stealth);

        total_stealth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_stealth.setText("0");
        add(total_stealth);

        lbl_arcanaName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_arcanaName.setText("Arcana (INT)");
        lbl_arcanaName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_arcanaName);

        prof_arcana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_arcana);

        bonus_arcana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_arcana.setText("0");
        add(bonus_arcana);

        total_arcana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_arcana.setText("0");
        add(total_arcana);

        lbl_historyName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_historyName.setText("History (INT)");
        lbl_historyName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_historyName);

        prof_history.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_history);

        bonus_history.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_history.setText("0");
        add(bonus_history);

        total_history.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_history.setText("0");
        add(total_history);

        lbl_investigationName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_investigationName.setText("Investigation (INT)");
        lbl_investigationName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_investigationName);

        prof_investigation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_investigation);

        bonus_investigation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_investigation.setText("0");
        add(bonus_investigation);

        total_investigation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_investigation.setText("0");
        add(total_investigation);

        lbl_natureName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_natureName.setText("Nature (INT)");
        lbl_natureName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_natureName);

        prof_nature.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_nature);

        bonus_nature.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_nature.setText("0");
        add(bonus_nature);

        total_nature.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_nature.setText("0");
        add(total_nature);

        lbl_religionName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_religionName.setText("Religion (INT)");
        lbl_religionName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_religionName);

        prof_religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_religion);

        bonus_religion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_religion.setText("0");
        add(bonus_religion);

        total_religion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_religion.setText("0");
        add(total_religion);

        lbl_animalHandlingName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_animalHandlingName.setText("Animal Handling (WIS)");
        lbl_animalHandlingName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_animalHandlingName);

        prof_animalHandling.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_animalHandling);

        bonus_animalHandling.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_animalHandling.setText("0");
        add(bonus_animalHandling);

        total_animalHandling.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_animalHandling.setText("0");
        add(total_animalHandling);

        lbl_insightName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_insightName.setText("Insight (WIS)");
        lbl_insightName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_insightName);

        prof_insight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_insight);

        bonus_insight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_insight.setText("0");
        add(bonus_insight);

        total_insight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_insight.setText("0");
        add(total_insight);

        lbl_medicineName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_medicineName.setText("Medicine (WIS)");
        lbl_medicineName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_medicineName);

        prof_medicine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_medicine);

        bonus_medicine.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_medicine.setText("0");
        add(bonus_medicine);

        total_medicine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_medicine.setText("0");
        add(total_medicine);

        lbl_perceptionName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_perceptionName.setText("Perception (WIS)");
        lbl_perceptionName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_perceptionName);

        prof_perception.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_perception);

        bonus_perception.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_perception.setText("0");
        add(bonus_perception);

        total_perception.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_perception.setText("0");
        add(total_perception);

        lbl_survivalName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_survivalName.setText("Survival (WIS)");
        lbl_survivalName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_survivalName);

        prof_survival.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_survival);

        bonus_survival.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_survival.setText("0");
        add(bonus_survival);

        total_survival.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_survival.setText("0");
        add(total_survival);

        lbl_deceptionName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_deceptionName.setText("Deception (CHA)");
        lbl_deceptionName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_deceptionName);

        prof_deception.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_deception);

        bonus_deception.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_deception.setText("0");
        add(bonus_deception);

        total_deception.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_deception.setText("0");
        add(total_deception);

        lbl_intimidationName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_intimidationName.setText("Intimidation (CHA)");
        lbl_intimidationName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_intimidationName);

        prof_intimidation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_intimidation);

        bonus_intimidation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_intimidation.setText("0");
        add(bonus_intimidation);

        total_intimidation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_intimidation.setText("0");
        add(total_intimidation);

        lbl_performanceName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_performanceName.setText("Performance (CHA)");
        lbl_performanceName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_performanceName);

        prof_performance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_performance);

        bonus_performance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_performance.setText("0");
        add(bonus_performance);

        total_performance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_performance.setText("0");
        add(total_performance);

        lbl_persuasionName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_persuasionName.setText("Persuasion (CHA)");
        lbl_persuasionName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl_persuasionName);

        prof_persuasion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "✓", "✓/2" }));
        add(prof_persuasion);

        bonus_persuasion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bonus_persuasion.setText("0");
        add(bonus_persuasion);

        total_persuasion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_persuasion.setText("0");
        add(total_persuasion);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bonus_acrobatics;
    private javax.swing.JTextField bonus_animalHandling;
    private javax.swing.JTextField bonus_arcana;
    private javax.swing.JTextField bonus_athletics;
    private javax.swing.JTextField bonus_deception;
    private javax.swing.JTextField bonus_history;
    private javax.swing.JTextField bonus_insight;
    private javax.swing.JTextField bonus_intimidation;
    private javax.swing.JTextField bonus_investigation;
    private javax.swing.JTextField bonus_medicine;
    private javax.swing.JTextField bonus_nature;
    private javax.swing.JTextField bonus_perception;
    private javax.swing.JTextField bonus_performance;
    private javax.swing.JTextField bonus_persuasion;
    private javax.swing.JTextField bonus_religion;
    private javax.swing.JTextField bonus_sleight;
    private javax.swing.JTextField bonus_stealth;
    private javax.swing.JTextField bonus_survival;
    private javax.swing.JLabel lbl_acrobaticsName;
    private javax.swing.JLabel lbl_animalHandlingName;
    private javax.swing.JLabel lbl_arcanaName;
    private javax.swing.JLabel lbl_athleticsName;
    private javax.swing.JLabel lbl_deceptionName;
    private javax.swing.JLabel lbl_historyName;
    private javax.swing.JLabel lbl_insightName;
    private javax.swing.JLabel lbl_intimidationName;
    private javax.swing.JLabel lbl_investigationName;
    private javax.swing.JLabel lbl_medicineName;
    private javax.swing.JLabel lbl_natureName;
    private javax.swing.JLabel lbl_perceptionName;
    private javax.swing.JLabel lbl_performanceName;
    private javax.swing.JLabel lbl_persuasionName;
    private javax.swing.JLabel lbl_religionName;
    private javax.swing.JLabel lbl_skillsColBonus;
    private javax.swing.JLabel lbl_skillsColName;
    private javax.swing.JLabel lbl_skillsColProf;
    private javax.swing.JLabel lbl_skillsColTotal;
    private javax.swing.JLabel lbl_sleightName;
    private javax.swing.JLabel lbl_stealthName;
    private javax.swing.JLabel lbl_survivalName;
    private javax.swing.JComboBox<String> prof_acrobatics;
    private javax.swing.JComboBox<String> prof_animalHandling;
    private javax.swing.JComboBox<String> prof_arcana;
    private javax.swing.JComboBox<String> prof_athletics;
    private javax.swing.JComboBox<String> prof_deception;
    private javax.swing.JComboBox<String> prof_history;
    private javax.swing.JComboBox<String> prof_insight;
    private javax.swing.JComboBox<String> prof_intimidation;
    private javax.swing.JComboBox<String> prof_investigation;
    private javax.swing.JComboBox<String> prof_medicine;
    private javax.swing.JComboBox<String> prof_nature;
    private javax.swing.JComboBox<String> prof_perception;
    private javax.swing.JComboBox<String> prof_performance;
    private javax.swing.JComboBox<String> prof_persuasion;
    private javax.swing.JComboBox<String> prof_religion;
    private javax.swing.JComboBox<String> prof_sleight;
    private javax.swing.JComboBox<String> prof_stealth;
    private javax.swing.JComboBox<String> prof_survival;
    private javax.swing.JLabel total_acrobatics;
    private javax.swing.JLabel total_animalHandling;
    private javax.swing.JLabel total_arcana;
    private javax.swing.JLabel total_athletics;
    private javax.swing.JLabel total_deception;
    private javax.swing.JLabel total_history;
    private javax.swing.JLabel total_insight;
    private javax.swing.JLabel total_intimidation;
    private javax.swing.JLabel total_investigation;
    private javax.swing.JLabel total_medicine;
    private javax.swing.JLabel total_nature;
    private javax.swing.JLabel total_perception;
    private javax.swing.JLabel total_performance;
    private javax.swing.JLabel total_persuasion;
    private javax.swing.JLabel total_religion;
    private javax.swing.JLabel total_sleight;
    private javax.swing.JLabel total_stealth;
    private javax.swing.JLabel total_survival;
    // End of variables declaration//GEN-END:variables

    void updateSkills(Bundle bundle) {
        if(bundle != null){
            int str_mod, dex_mod, int_mod, wis_mod, cha_mod;
            int prof_bonus;
            str_mod = bundle.getInteger(KEY.K_STRENGTH);
            dex_mod = bundle.getInteger(KEY.K_DEXTERITY);
            int_mod = bundle.getInteger(KEY.K_INTELLIGENCE);
            wis_mod = bundle.getInteger(KEY.K_WISDOM);
            cha_mod = bundle.getInteger(KEY.K_CHARISMA);
            prof_bonus = bundle.getInteger(KEY.K_PROFICIENCY_BONUS);
            
            setTotal(bonus_acrobatics, prof_acrobatics, dex_mod, prof_bonus, total_acrobatics);
            setTotal(bonus_animalHandling, prof_animalHandling, wis_mod, prof_bonus, total_animalHandling);
            setTotal(bonus_arcana, prof_arcana, int_mod, prof_bonus, total_arcana);
            setTotal(bonus_athletics, prof_athletics, str_mod, prof_bonus, total_athletics);
            setTotal(bonus_deception, prof_deception, cha_mod, prof_bonus, total_deception);
            setTotal(bonus_history, prof_history, int_mod, prof_bonus, total_history);
            setTotal(bonus_insight, prof_insight, wis_mod, prof_bonus, total_insight);
            setTotal(bonus_intimidation, prof_intimidation, cha_mod, prof_bonus, total_intimidation);
            setTotal(bonus_investigation, prof_investigation, int_mod, prof_bonus, total_investigation);
            setTotal(bonus_medicine, prof_medicine, int_mod, prof_bonus, total_medicine);
            setTotal(bonus_nature, prof_nature, wis_mod, prof_bonus, total_nature);
            setTotal(bonus_perception, prof_perception, wis_mod, prof_bonus, total_perception);
            setTotal(bonus_performance, prof_performance, cha_mod, prof_bonus, total_performance);
            setTotal(bonus_persuasion, prof_persuasion, cha_mod, prof_bonus, total_persuasion);
            setTotal(bonus_religion, prof_religion, wis_mod, prof_bonus, total_religion);
            setTotal(bonus_sleight, prof_sleight, dex_mod, prof_bonus, total_sleight);
            setTotal(bonus_stealth, prof_stealth, dex_mod, prof_bonus, total_stealth);
            setTotal(bonus_survival, prof_survival, wis_mod, prof_bonus, total_survival);
        }
    }

    void initListenerForSkills(AppManager manager) {
        setTextListener(bonus_acrobatics, KEY.K_ACROBATICS_BONUS, manager);
        setTextListener(bonus_animalHandling, KEY.K_ANIMAL_BONUS, manager);
        setTextListener(bonus_arcana, KEY.K_ARCANA_BONUS, manager);
        setTextListener(bonus_athletics, KEY.K_ATHLETICS_BONUS, manager);
        setTextListener(bonus_deception, KEY.K_DECEPTION_BONUS, manager);
        setTextListener(bonus_history, KEY.K_HISTORY_BONUS, manager);
        setTextListener(bonus_insight, KEY.K_INSIGHT_BONUS, manager);
        setTextListener(bonus_intimidation, KEY.K_INTIMIDATION_BONUS, manager);
        setTextListener(bonus_investigation, KEY.K_INVESTIGATION_BONUS, manager);
        setTextListener(bonus_medicine, KEY.K_MEDICINE_BONUS, manager);
        setTextListener(bonus_nature, KEY.K_NATURE_BONUS, manager);
        setTextListener(bonus_perception, KEY.K_PERCEPTION_BONUS, manager);
        setTextListener(bonus_performance, KEY.K_PERFORMANCE_BONUS, manager);
        setTextListener(bonus_persuasion, KEY.K_PERSUASION_BONUS, manager);
        setTextListener(bonus_religion, KEY.K_RELIGION_BONUS, manager);
        setTextListener(bonus_sleight, KEY.K_SLEIGHT_BONUS, manager);
        setTextListener(bonus_stealth, KEY.K_STEALTH_BONUS, manager);
        setTextListener(bonus_survival, KEY.K_SURVIVAL_BONUS, manager);
        
        setComboBoxListener(prof_acrobatics, manager);
        setComboBoxListener(prof_animalHandling, manager);
        setComboBoxListener(prof_arcana, manager);
        setComboBoxListener(prof_athletics, manager);
        setComboBoxListener(prof_deception, manager);
        setComboBoxListener(prof_history, manager);
        setComboBoxListener(prof_insight, manager);
        setComboBoxListener(prof_intimidation, manager);
        setComboBoxListener(prof_investigation, manager);
        setComboBoxListener(prof_medicine, manager);
        setComboBoxListener(prof_nature, manager);
        setComboBoxListener(prof_perception, manager);
        setComboBoxListener(prof_religion, manager);
        setComboBoxListener(prof_sleight, manager);
        setComboBoxListener(prof_stealth, manager);
        setComboBoxListener(prof_survival, manager);
    }
    
    private void setTextListener(JTextComponent component, String key, AppManager manager) {
        component.addFocusListener(new TextFocusListener(key, component.getDocument(), manager));
    }

    private void setTotal
        (JTextField bonus, 
        JComboBox<String> prof_type, 
        int attr_mod, 
        int prof_bonus, 
        JLabel total_field) 
        {
            switch((String) prof_type.getSelectedItem()){
                case "X":prof_bonus=0;break;
                case "✓":prof_bonus=prof_bonus;break;
                case "✓/2":prof_bonus = prof_bonus/2;break;
                default:prof_bonus=0;
            }
            
            int bon = Integer.parseInt(bonus.getText());
            int total = attr_mod + bon + prof_bonus;
            total_field.setText(Integer.toString(total));
        }

    private void setComboBoxListener(JComboBox<String> combo, AppManager manager) {
        combo.addItemListener(new ComboItemListener(manager));
    }
}
