/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.character_sheet;

import app.AppManager;
import gui.util.KEY;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import data_structure.Spell;
import data_structure.Spellbook;

/**
 *
 * @author Kendrick-Laptop
 */
public class SpellbookFrame extends javax.swing.JFrame {

    /**
     * Creates new form Spellbook
     */
    public SpellbookFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_pane = new javax.swing.JTabbedPane();
        pan_cant = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_0 = new javax.swing.JTable();
        pan_dc = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_dc = new javax.swing.JLabel();
        lbl_dc_num0 = new javax.swing.JLabel();
        pan_interaction = new javax.swing.JPanel();
        add_row0 = new javax.swing.JButton();
        rem_row0 = new javax.swing.JButton();
        pan1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_1 = new javax.swing.JTable();
        pan_dc1 = new javax.swing.JPanel();
        pan_interaction1 = new javax.swing.JPanel();
        add_row1 = new javax.swing.JButton();
        rem_row1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_dc10 = new javax.swing.JLabel();
        lbl_dc_num1 = new javax.swing.JLabel();
        pan2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_2 = new javax.swing.JTable();
        pan_dc2 = new javax.swing.JPanel();
        pan_interaction2 = new javax.swing.JPanel();
        add_row2 = new javax.swing.JButton();
        rem_row2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbl_dc11 = new javax.swing.JLabel();
        lbl_dc_num2 = new javax.swing.JLabel();
        pan3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_3 = new javax.swing.JTable();
        pan_dc3 = new javax.swing.JPanel();
        pan_interaction3 = new javax.swing.JPanel();
        add_row3 = new javax.swing.JButton();
        rem_row3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lbl_dc12 = new javax.swing.JLabel();
        lbl_dc_num3 = new javax.swing.JLabel();
        pan4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_4 = new javax.swing.JTable();
        pan_dc4 = new javax.swing.JPanel();
        pan_interaction4 = new javax.swing.JPanel();
        add_row4 = new javax.swing.JButton();
        rem_row4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lbl_dc13 = new javax.swing.JLabel();
        lbl_dc_num4 = new javax.swing.JLabel();
        pan5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_5 = new javax.swing.JTable();
        pan_dc5 = new javax.swing.JPanel();
        pan_interaction5 = new javax.swing.JPanel();
        add_row5 = new javax.swing.JButton();
        rem_row5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lbl_dc14 = new javax.swing.JLabel();
        lbl_dc_num5 = new javax.swing.JLabel();
        pan6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl_6 = new javax.swing.JTable();
        pan_dc6 = new javax.swing.JPanel();
        pan_interaction6 = new javax.swing.JPanel();
        add_row6 = new javax.swing.JButton();
        rem_row6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        lbl_dc15 = new javax.swing.JLabel();
        lbl_dc_num6 = new javax.swing.JLabel();
        pan7 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbl_7 = new javax.swing.JTable();
        pan_dc7 = new javax.swing.JPanel();
        pan_interaction7 = new javax.swing.JPanel();
        add_row7 = new javax.swing.JButton();
        rem_row7 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        lbl_dc16 = new javax.swing.JLabel();
        lbl_dc_num7 = new javax.swing.JLabel();
        pan8 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tbl_8 = new javax.swing.JTable();
        pan_dc8 = new javax.swing.JPanel();
        pan_interaction8 = new javax.swing.JPanel();
        add_row8 = new javax.swing.JButton();
        rem_row8 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        lbl_dc17 = new javax.swing.JLabel();
        lbl_dc_num8 = new javax.swing.JLabel();
        pan9 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tbl_9 = new javax.swing.JTable();
        pan_dc9 = new javax.swing.JPanel();
        pan_interaction9 = new javax.swing.JPanel();
        add_row9 = new javax.swing.JButton();
        rem_row9 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        lbl_dc18 = new javax.swing.JLabel();
        lbl_dc_num9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_caster_type = new javax.swing.JLabel();
        combo_caster = new javax.swing.JComboBox<>();

        setTitle("Spellbook");
        setMinimumSize(new java.awt.Dimension(500, 300));
        setResizable(false);

        tab_pane.setPreferredSize(new java.awt.Dimension(600, 463));

        pan_cant.setLayout(new java.awt.BorderLayout());

        tbl_0.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Spell", "Description"
            }
        ));
        jScrollPane1.setViewportView(tbl_0);

        pan_cant.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pan_dc.setLayout(new java.awt.BorderLayout());

        lbl_dc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dc.setText("Spell DC:");
        jPanel1.add(lbl_dc);

        lbl_dc_num0.setText("10");
        jPanel1.add(lbl_dc_num0);

        pan_dc.add(jPanel1, java.awt.BorderLayout.CENTER);

        add_row0.setText("Add Row");
        add_row0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_row0ActionPerformed(evt);
            }
        });
        pan_interaction.add(add_row0);

        rem_row0.setText("Remove Row");
        rem_row0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rem_row0ActionPerformed(evt);
            }
        });
        pan_interaction.add(rem_row0);

        pan_dc.add(pan_interaction, java.awt.BorderLayout.LINE_END);

        pan_cant.add(pan_dc, java.awt.BorderLayout.PAGE_START);

        tab_pane.addTab("Cantrips", pan_cant);

        pan1.setLayout(new java.awt.BorderLayout());

        tbl_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Spell", "Description"
            }
        ));
        jScrollPane2.setViewportView(tbl_1);

        pan1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pan_dc1.setLayout(new java.awt.BorderLayout());

        add_row1.setText("Add Row");
        add_row1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_row1ActionPerformed(evt);
            }
        });
        pan_interaction1.add(add_row1);

        rem_row1.setText("Remove Row");
        rem_row1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rem_row1ActionPerformed(evt);
            }
        });
        pan_interaction1.add(rem_row1);

        pan_dc1.add(pan_interaction1, java.awt.BorderLayout.LINE_END);

        lbl_dc10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dc10.setText("Spell DC:");
        jPanel3.add(lbl_dc10);

        lbl_dc_num1.setText("10");
        jPanel3.add(lbl_dc_num1);

        pan_dc1.add(jPanel3, java.awt.BorderLayout.CENTER);

        pan1.add(pan_dc1, java.awt.BorderLayout.PAGE_START);

        tab_pane.addTab("Level 1 ", pan1);

        pan2.setLayout(new java.awt.BorderLayout());

        tbl_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Spell", "Description"
            }
        ));
        jScrollPane3.setViewportView(tbl_2);

        pan2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        pan_dc2.setLayout(new java.awt.BorderLayout());

        add_row2.setText("Add Row");
        add_row2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_row2ActionPerformed(evt);
            }
        });
        pan_interaction2.add(add_row2);

        rem_row2.setText("Remove Row");
        rem_row2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rem_row2ActionPerformed(evt);
            }
        });
        pan_interaction2.add(rem_row2);

        pan_dc2.add(pan_interaction2, java.awt.BorderLayout.LINE_END);

        lbl_dc11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dc11.setText("Spell DC:");
        jPanel4.add(lbl_dc11);

        lbl_dc_num2.setText("10");
        jPanel4.add(lbl_dc_num2);

        pan_dc2.add(jPanel4, java.awt.BorderLayout.CENTER);

        pan2.add(pan_dc2, java.awt.BorderLayout.PAGE_START);

        tab_pane.addTab("Level 2", pan2);

        pan3.setLayout(new java.awt.BorderLayout());

        tbl_3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Spell", "Description"
            }
        ));
        jScrollPane4.setViewportView(tbl_3);

        pan3.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        pan_dc3.setLayout(new java.awt.BorderLayout());

        add_row3.setText("Add Row");
        add_row3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_row3ActionPerformed(evt);
            }
        });
        pan_interaction3.add(add_row3);

        rem_row3.setText("Remove Row");
        rem_row3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rem_row3ActionPerformed(evt);
            }
        });
        pan_interaction3.add(rem_row3);

        pan_dc3.add(pan_interaction3, java.awt.BorderLayout.LINE_END);

        lbl_dc12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dc12.setText("Spell DC:");
        jPanel5.add(lbl_dc12);

        lbl_dc_num3.setText("10");
        jPanel5.add(lbl_dc_num3);

        pan_dc3.add(jPanel5, java.awt.BorderLayout.CENTER);

        pan3.add(pan_dc3, java.awt.BorderLayout.PAGE_START);

        tab_pane.addTab("Level 3", pan3);

        pan4.setLayout(new java.awt.BorderLayout());

        tbl_4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Spell", "Description"
            }
        ));
        jScrollPane5.setViewportView(tbl_4);

        pan4.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        pan_dc4.setLayout(new java.awt.BorderLayout());

        add_row4.setText("Add Row");
        add_row4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_row4ActionPerformed(evt);
            }
        });
        pan_interaction4.add(add_row4);

        rem_row4.setText("Remove Row");
        rem_row4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rem_row4ActionPerformed(evt);
            }
        });
        pan_interaction4.add(rem_row4);

        pan_dc4.add(pan_interaction4, java.awt.BorderLayout.LINE_END);

        lbl_dc13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dc13.setText("Spell DC:");
        jPanel6.add(lbl_dc13);

        lbl_dc_num4.setText("10");
        jPanel6.add(lbl_dc_num4);

        pan_dc4.add(jPanel6, java.awt.BorderLayout.CENTER);

        pan4.add(pan_dc4, java.awt.BorderLayout.PAGE_START);

        tab_pane.addTab("Level 4", pan4);

        pan5.setLayout(new java.awt.BorderLayout());

        tbl_5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Spell", "Description"
            }
        ));
        jScrollPane6.setViewportView(tbl_5);

        pan5.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        pan_dc5.setLayout(new java.awt.BorderLayout());

        add_row5.setText("Add Row");
        add_row5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_row5ActionPerformed(evt);
            }
        });
        pan_interaction5.add(add_row5);

        rem_row5.setText("Remove Row");
        rem_row5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rem_row5ActionPerformed(evt);
            }
        });
        pan_interaction5.add(rem_row5);

        pan_dc5.add(pan_interaction5, java.awt.BorderLayout.LINE_END);

        lbl_dc14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dc14.setText("Spell DC:");
        jPanel7.add(lbl_dc14);

        lbl_dc_num5.setText("10");
        jPanel7.add(lbl_dc_num5);

        pan_dc5.add(jPanel7, java.awt.BorderLayout.CENTER);

        pan5.add(pan_dc5, java.awt.BorderLayout.PAGE_START);

        tab_pane.addTab("Level 5", pan5);

        pan6.setLayout(new java.awt.BorderLayout());

        tbl_6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Spell", "Description"
            }
        ));
        jScrollPane7.setViewportView(tbl_6);

        pan6.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        pan_dc6.setLayout(new java.awt.BorderLayout());

        add_row6.setText("Add Row");
        add_row6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_row6ActionPerformed(evt);
            }
        });
        pan_interaction6.add(add_row6);

        rem_row6.setText("Remove Row");
        rem_row6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rem_row6ActionPerformed(evt);
            }
        });
        pan_interaction6.add(rem_row6);

        pan_dc6.add(pan_interaction6, java.awt.BorderLayout.LINE_END);

        lbl_dc15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dc15.setText("Spell DC:");
        jPanel8.add(lbl_dc15);

        lbl_dc_num6.setText("10");
        jPanel8.add(lbl_dc_num6);

        pan_dc6.add(jPanel8, java.awt.BorderLayout.CENTER);

        pan6.add(pan_dc6, java.awt.BorderLayout.PAGE_START);

        tab_pane.addTab("Level 6", pan6);

        pan7.setLayout(new java.awt.BorderLayout());

        tbl_7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Spell", "Description"
            }
        ));
        jScrollPane8.setViewportView(tbl_7);

        pan7.add(jScrollPane8, java.awt.BorderLayout.CENTER);

        pan_dc7.setLayout(new java.awt.BorderLayout());

        add_row7.setText("Add Row");
        add_row7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_row7ActionPerformed(evt);
            }
        });
        pan_interaction7.add(add_row7);

        rem_row7.setText("Remove Row");
        rem_row7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rem_row7ActionPerformed(evt);
            }
        });
        pan_interaction7.add(rem_row7);

        pan_dc7.add(pan_interaction7, java.awt.BorderLayout.LINE_END);

        lbl_dc16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dc16.setText("Spell DC:");
        jPanel9.add(lbl_dc16);

        lbl_dc_num7.setText("10");
        jPanel9.add(lbl_dc_num7);

        pan_dc7.add(jPanel9, java.awt.BorderLayout.CENTER);

        pan7.add(pan_dc7, java.awt.BorderLayout.PAGE_START);

        tab_pane.addTab("Level 7", pan7);

        pan8.setLayout(new java.awt.BorderLayout());

        tbl_8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Spell", "Description"
            }
        ));
        jScrollPane9.setViewportView(tbl_8);

        pan8.add(jScrollPane9, java.awt.BorderLayout.CENTER);

        pan_dc8.setLayout(new java.awt.BorderLayout());

        add_row8.setText("Add Row");
        add_row8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_row8ActionPerformed(evt);
            }
        });
        pan_interaction8.add(add_row8);

        rem_row8.setText("Remove Row");
        rem_row8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rem_row8ActionPerformed(evt);
            }
        });
        pan_interaction8.add(rem_row8);

        pan_dc8.add(pan_interaction8, java.awt.BorderLayout.LINE_END);

        lbl_dc17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dc17.setText("Spell DC:");
        jPanel10.add(lbl_dc17);

        lbl_dc_num8.setText("10");
        jPanel10.add(lbl_dc_num8);

        pan_dc8.add(jPanel10, java.awt.BorderLayout.CENTER);

        pan8.add(pan_dc8, java.awt.BorderLayout.PAGE_START);

        tab_pane.addTab("Level 8", pan8);

        pan9.setLayout(new java.awt.BorderLayout());

        tbl_9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Spell", "Description"
            }
        ));
        jScrollPane10.setViewportView(tbl_9);

        pan9.add(jScrollPane10, java.awt.BorderLayout.CENTER);

        pan_dc9.setLayout(new java.awt.BorderLayout());

        add_row9.setText("Add Row");
        add_row9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_row9ActionPerformed(evt);
            }
        });
        pan_interaction9.add(add_row9);

        rem_row9.setText("Remove Row");
        rem_row9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rem_row9ActionPerformed(evt);
            }
        });
        pan_interaction9.add(rem_row9);

        pan_dc9.add(pan_interaction9, java.awt.BorderLayout.LINE_END);

        lbl_dc18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dc18.setText("Spell DC:");
        jPanel11.add(lbl_dc18);

        lbl_dc_num9.setText("10");
        jPanel11.add(lbl_dc_num9);

        pan_dc9.add(jPanel11, java.awt.BorderLayout.CENTER);

        pan9.add(pan_dc9, java.awt.BorderLayout.PAGE_START);

        tab_pane.addTab("Level 9 ", pan9);

        getContentPane().add(tab_pane, java.awt.BorderLayout.CENTER);

        lbl_caster_type.setText("Caster Type");
        jPanel2.add(lbl_caster_type);

        combo_caster.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intelligence", "Wisdom", "Charisma" }));
        combo_caster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_casterActionPerformed(evt);
            }
        });
        jPanel2.add(combo_caster);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_row0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_row0ActionPerformed
        addRow(tbl_0);
    }//GEN-LAST:event_add_row0ActionPerformed

    private void rem_row0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rem_row0ActionPerformed
        remRow(tbl_0);
    }//GEN-LAST:event_rem_row0ActionPerformed

    private void add_row1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_row1ActionPerformed
        addRow(tbl_1);
    }//GEN-LAST:event_add_row1ActionPerformed

    private void rem_row1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rem_row1ActionPerformed
        remRow(tbl_1);
    }//GEN-LAST:event_rem_row1ActionPerformed

    private void add_row2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_row2ActionPerformed
        addRow(tbl_2);
    }//GEN-LAST:event_add_row2ActionPerformed

    private void rem_row2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rem_row2ActionPerformed
        remRow(tbl_2);
    }//GEN-LAST:event_rem_row2ActionPerformed

    private void add_row3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_row3ActionPerformed
        addRow(tbl_3);
    }//GEN-LAST:event_add_row3ActionPerformed

    private void rem_row3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rem_row3ActionPerformed
        remRow(tbl_3);
    }//GEN-LAST:event_rem_row3ActionPerformed

    private void add_row4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_row4ActionPerformed
        addRow(tbl_4);
    }//GEN-LAST:event_add_row4ActionPerformed

    private void rem_row4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rem_row4ActionPerformed
        remRow(tbl_4);
    }//GEN-LAST:event_rem_row4ActionPerformed

    private void add_row5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_row5ActionPerformed
        addRow(tbl_5);
    }//GEN-LAST:event_add_row5ActionPerformed

    private void rem_row5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rem_row5ActionPerformed
        remRow(tbl_5);
    }//GEN-LAST:event_rem_row5ActionPerformed

    private void add_row6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_row6ActionPerformed
        addRow(tbl_6);
    }//GEN-LAST:event_add_row6ActionPerformed

    private void rem_row6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rem_row6ActionPerformed
        remRow(tbl_6);
    }//GEN-LAST:event_rem_row6ActionPerformed

    private void add_row7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_row7ActionPerformed
        addRow(tbl_7);
    }//GEN-LAST:event_add_row7ActionPerformed

    private void rem_row7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rem_row7ActionPerformed
        remRow(tbl_7);
    }//GEN-LAST:event_rem_row7ActionPerformed

    private void add_row8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_row8ActionPerformed
        addRow(tbl_8);
    }//GEN-LAST:event_add_row8ActionPerformed

    private void rem_row8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rem_row8ActionPerformed
        remRow(tbl_8);
    }//GEN-LAST:event_rem_row8ActionPerformed

    private void add_row9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_row9ActionPerformed
        addRow(tbl_9);
    }//GEN-LAST:event_add_row9ActionPerformed

    private void rem_row9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rem_row9ActionPerformed
        remRow(tbl_9);
    }//GEN-LAST:event_rem_row9ActionPerformed

    private void combo_casterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_casterActionPerformed
        AppManager.getInstance().updateValues();
    }//GEN-LAST:event_combo_casterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_row0;
    private javax.swing.JButton add_row1;
    private javax.swing.JButton add_row2;
    private javax.swing.JButton add_row3;
    private javax.swing.JButton add_row4;
    private javax.swing.JButton add_row5;
    private javax.swing.JButton add_row6;
    private javax.swing.JButton add_row7;
    private javax.swing.JButton add_row8;
    private javax.swing.JButton add_row9;
    private javax.swing.JComboBox<String> combo_caster;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lbl_caster_type;
    private javax.swing.JLabel lbl_dc;
    private javax.swing.JLabel lbl_dc10;
    private javax.swing.JLabel lbl_dc11;
    private javax.swing.JLabel lbl_dc12;
    private javax.swing.JLabel lbl_dc13;
    private javax.swing.JLabel lbl_dc14;
    private javax.swing.JLabel lbl_dc15;
    private javax.swing.JLabel lbl_dc16;
    private javax.swing.JLabel lbl_dc17;
    private javax.swing.JLabel lbl_dc18;
    private javax.swing.JLabel lbl_dc_num0;
    private javax.swing.JLabel lbl_dc_num1;
    private javax.swing.JLabel lbl_dc_num2;
    private javax.swing.JLabel lbl_dc_num3;
    private javax.swing.JLabel lbl_dc_num4;
    private javax.swing.JLabel lbl_dc_num5;
    private javax.swing.JLabel lbl_dc_num6;
    private javax.swing.JLabel lbl_dc_num7;
    private javax.swing.JLabel lbl_dc_num8;
    private javax.swing.JLabel lbl_dc_num9;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JPanel pan3;
    private javax.swing.JPanel pan4;
    private javax.swing.JPanel pan5;
    private javax.swing.JPanel pan6;
    private javax.swing.JPanel pan7;
    private javax.swing.JPanel pan8;
    private javax.swing.JPanel pan9;
    private javax.swing.JPanel pan_cant;
    private javax.swing.JPanel pan_dc;
    private javax.swing.JPanel pan_dc1;
    private javax.swing.JPanel pan_dc2;
    private javax.swing.JPanel pan_dc3;
    private javax.swing.JPanel pan_dc4;
    private javax.swing.JPanel pan_dc5;
    private javax.swing.JPanel pan_dc6;
    private javax.swing.JPanel pan_dc7;
    private javax.swing.JPanel pan_dc8;
    private javax.swing.JPanel pan_dc9;
    private javax.swing.JPanel pan_interaction;
    private javax.swing.JPanel pan_interaction1;
    private javax.swing.JPanel pan_interaction2;
    private javax.swing.JPanel pan_interaction3;
    private javax.swing.JPanel pan_interaction4;
    private javax.swing.JPanel pan_interaction5;
    private javax.swing.JPanel pan_interaction6;
    private javax.swing.JPanel pan_interaction7;
    private javax.swing.JPanel pan_interaction8;
    private javax.swing.JPanel pan_interaction9;
    private javax.swing.JButton rem_row0;
    private javax.swing.JButton rem_row1;
    private javax.swing.JButton rem_row2;
    private javax.swing.JButton rem_row3;
    private javax.swing.JButton rem_row4;
    private javax.swing.JButton rem_row5;
    private javax.swing.JButton rem_row6;
    private javax.swing.JButton rem_row7;
    private javax.swing.JButton rem_row8;
    private javax.swing.JButton rem_row9;
    private javax.swing.JTabbedPane tab_pane;
    private javax.swing.JTable tbl_0;
    private javax.swing.JTable tbl_1;
    private javax.swing.JTable tbl_2;
    private javax.swing.JTable tbl_3;
    private javax.swing.JTable tbl_4;
    private javax.swing.JTable tbl_5;
    private javax.swing.JTable tbl_6;
    private javax.swing.JTable tbl_7;
    private javax.swing.JTable tbl_8;
    private javax.swing.JTable tbl_9;
    // End of variables declaration//GEN-END:variables

    private void addRow(JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.addRow(new Object[] {null, null});
        table.setRowSelectionInterval(model.getRowCount()-1, model.getRowCount()-1);
    }
    
    private void remRow(JTable table){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int row = table.getSelectedRow();
        if(row != -1){
            model.removeRow(row);
            if(model.getRowCount() > 0){
                if(row == 0){
                    row = 1;
                }
                table.setRowSelectionInterval(row-1, row-1);
            }
        }
    }
    
    public Spellbook getSpellbook(){
        Spellbook book = new Spellbook(combo_caster.getSelectedIndex());
        ArrayList<Spell> cantrips,first,second,third,fourth,fifth,sixth,seventh,eighth,ninth;
        cantrips = collectSpells(tbl_0);
        first = collectSpells(tbl_1);
        second = collectSpells(tbl_2);
        third = collectSpells(tbl_3);
        fourth = collectSpells(tbl_4);
        fifth = collectSpells(tbl_5);
        sixth = collectSpells(tbl_6);
        seventh = collectSpells(tbl_7);
        eighth = collectSpells(tbl_8);
        ninth = collectSpells(tbl_9);
        
        book.addSpellsCollection(cantrips);
        book.addSpellsCollection(first);
        book.addSpellsCollection(second);
        book.addSpellsCollection(third);
        book.addSpellsCollection(fourth);
        book.addSpellsCollection(fifth);
        book.addSpellsCollection(sixth);
        book.addSpellsCollection(seventh);
        book.addSpellsCollection(eighth);
        book.addSpellsCollection(ninth);
        
        return book;
    }
    
    public void updateSpellbook(Spellbook book){
        if(book != null){
            int index = book.getCasterType();
            combo_caster.setSelectedIndex(index);
            for(int lvl = 0;lvl < book.length(); lvl++){
                ArrayList<Spell> spells = book.getCollection(lvl);
                JTable table= null;
                switch(lvl){
                    case 0:table=tbl_0;break;
                    case 1:table=tbl_1;break;
                    case 2:table=tbl_2;break;
                    case 3:table=tbl_3;break;
                    case 4:table=tbl_4;break;
                    case 5:table=tbl_5;break;
                    case 6:table=tbl_6;break;
                    case 7:table=tbl_7;break;
                    case 8:table=tbl_8;break;
                    case 9:table=tbl_9;break;
                }
                
                if(table != null){
                    updateSpells(spells, table);
                }
            }
        }
    }

    private ArrayList<Spell> collectSpells(JTable table) {
        ArrayList<Spell> spells = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        for(int row = 0; row < model.getRowCount(); row++){
            String name = (String) model.getValueAt(row, 0);
            String desc = (String) model.getValueAt(row, 1);
            
            spells.add(new Spell(name, desc));
        }
        return spells;
    }

    private void updateSpells(ArrayList<Spell> spells, JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        while(model.getRowCount() > 0){
            model.removeRow(0);
        }
        
        for(int i = 0; i < spells.size(); i++){
            Spell spell = spells.get(i);
            model.insertRow(i, new Object[] {spell.name, spell.description});
        }
    }

    String getCasterType() {
        int row = combo_caster.getSelectedIndex();
        switch(row){
            case 0:return KEY.K_INTELLIGENCE;
            case 1:return KEY.K_WISDOM;
            case 2:return KEY.K_CHARISMA;
        }
        return "";
    }

    void updateSpellDC(int mod) {
        int dc;
        JLabel lbl = null;
        for(int i = 0;i < 10; i++){
            dc = 10+i+mod;
            switch(i){
                case 0:lbl=lbl_dc_num0;break;
                case 1:lbl=lbl_dc_num1;break;
                case 2:lbl=lbl_dc_num2;break;
                case 3:lbl=lbl_dc_num3;break;
                case 4:lbl=lbl_dc_num4;break;
                case 5:lbl=lbl_dc_num5;break;
                case 6:lbl=lbl_dc_num6;break;
                case 7:lbl=lbl_dc_num7;break;
                case 8:lbl=lbl_dc_num8;break;
                case 9:lbl=lbl_dc_num9;break;
            }
            updateDCLabel(lbl, dc);
        }
    }

    private void updateDCLabel(JLabel lbl, int dc) {
        if(lbl != null){
            lbl.setText(Integer.toString(dc));
        }
    }
}
